version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: CMake
          command: mkdir build; cmake ..; make;
      - run:
          name: Run the Test
          command: make test
